"""empty message

Revision ID: 152711d78c57
Revises: 
Create Date: 2020-05-26 14:40:12.827298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152711d78c57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name_first', sa.String(length=60), nullable=True))
    op.add_column('user', sa.Column('name_last', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name_last')
    op.drop_column('user', 'name_first')
    # ### end Alembic commands ###
