"""empty message

Revision ID: 494327a9a490
Revises: 8d6a5e796bdd
Create Date: 2020-07-10 14:34:53.038108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494327a9a490'
down_revision = '8d6a5e796bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'user_id')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'relationship', 'people', ['user_two_id'], ['id'])
    op.create_foreign_key(None, 'relationship', 'people', ['user_one_id'], ['id'])
    op.add_column('people', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
