"""empty message

Revision ID: 659c83593639
Revises: 152711d78c57
Create Date: 2020-05-27 01:19:24.383594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659c83593639'
down_revision = '152711d78c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('father', sa.Column('father_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('father', 'father_user_id')
    # ### end Alembic commands ###
