"""empty message

Revision ID: d0635a92462f
Revises: 494327a9a490
Create Date: 2020-07-10 14:39:34.934104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0635a92462f'
down_revision = '494327a9a490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'user_id')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    op.drop_constraint(None, 'relationship', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'relationship', 'people', ['user_one_id'], ['id'])
    op.create_foreign_key(None, 'relationship', 'people', ['user_two_id'], ['id'])
    op.add_column('people', sa.Column('user_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
