"""empty message

Revision ID: dfcd97f33f39
Revises: 659c83593639
Create Date: 2020-05-27 02:48:47.316998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcd97f33f39'
down_revision = '659c83593639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mother', sa.Column('mother_user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mother', 'mother_user_id')
    # ### end Alembic commands ###
